#pragma once

#define типа {
#define Єба }
#define внатуре ==
#define базарь cout
#define спроси cin
#define сюда >>
#define туда <<
#define бл€ть ;
#define ещЄ ,
#define чЄтко true
#define хуево false
#define если if
#define иначе else
#define пизже >
#define хуЄвей <
#define и &&
#define или ||
#define не !
#define лысый unsigned
#define нормальный signed
#define целый int
#define дробный double
#define целый_децл short
#define дробный_децл float
#define доху€ long
#define доху€_целый long
#define децл char
#define дегенерат bool
#define пиздуй goto
#define Єбни break
#define продолжь continue
#define дл€ for
#define пока while
#define ебашь do
#define передай return
#define пон€тие const
#define пацан class
#define чикса struct
#define ньюфаг new
#define дЄрни try
#define слови catch
#define пиздани throw
#define кент friend
#define район namespace
#define нычка private
#define фраерское public
#define пацанское protected
#define общий static
#define вертолЄт virtual
#define € this
#define бицуха sizeof
#define отпизди delete
#define позови using
#define братки :
#define братуха :
#define ниху€ void
#define хуйн€ nullptr
#define спизди extern
#define распиздуй switch
#define случай case
#define пиздец default
#define шн€га enum
#define возьми ->