#pragma once

#define типа {
#define ёба }
#define внатуре ==
#define базарь cout
#define поясни cin
#define сюда >>
#define туда <<
#define блять ;
#define ещё ,
#define чётко true
#define хуево false
#define если if
#define иначе else
#define пизже >
#define хуёвей <
#define бля_и_бля &&
#define бля_или_бля ||
#define бля_нет_бля !
#define лысый unsigned
#define нормальный signed
#define целый int
#define дробный double
#define целый_децл short
#define дробный_децл float
#define дохуя long
#define дохуя_целый long
#define децл char
#define дегенерат bool
#define пиздуй goto
#define ёбни break
#define продолжь continue
#define для for
#define пока while
#define ебашь do
#define передай return
#define понятие const
#define пацан class
#define чикса struct
#define ньюфаг new
#define дёрни try
#define слови catch
#define пиздани throw
#define кент friend
#define район namespace
#define нычка private
#define фраерское public
#define пацанское protected
#define общий static
#define вертолёт virtual
#define бля_я_нахуй this
#define бицуха sizeof
#define отпизди delete
#define позови using
#define братки :
#define братуха :
#define нихуя void
#define хуйня nullptr
#define спизди extern
#define распиздуй switch
#define случай case
#define пиздец default
#define шняга enum
#define возьми ->
#define пахан main
#define четкие_кенты std
#define ёпта )
#define базаришь (
